#! /bin/sh

sxhkd &
compton &

bspc monitor DP-1 -d 1 2 3 4 5
bspc monitor DP-2 -d 6 7 8 9 10


bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

sh /home/eliraz/.config/polybar/launch.sh
feh --bg-scale /usr/share/archlinux/wallpaper/archlinux-elation.jpg
setxkbmap us,il -option grp:alt_space_toggle